### PR TITLE
Bcrypt added and argon removed and sequilize reverted

### PR DESCRIPTION
**Pull request by mustafapc19**

### CODE REVIEW

**Comment by mustafapc19** [comment]
Populate users with register route as old hash may persist in the old database

**Comment by jilvin** [comment]
Why was argon removed? Isn't argon2 better?

**Comment by mustafapc19** [comment]
Argon is slow. It was taking 5 seconds just to hash. While bcrypt hashes in below 1 second.

**Comment by jilvin** [comment]
I think it was intentional. Can you read on before you merge?

**Comment by mustafapc19** [comment]
I have read on.I dont think relativly weak password hash will be that big of a deal as server will be hanging all the time under argon. I think its a good compromise. My friend ka laptop hangs when he accesses login api :smile:

**Comment by jilvin** [comment]
You can try tweaking the parameters when you guys get time. There will be a trade off anyway but argon2 was specifically designed against some known attacks.

**Comment by mustafapc19** [comment]
I tried the default setting but it was slow as well. And to brute force wont they need to know the password before hand? So I dont think it will a big deal based. And the time delay is pain in ass for development. Might change before shipping maybe. Idk

**Pull request merged**
